services:
  web:
    platform: linux/arm64
    restart: always
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web/src:/myfolder/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.docker
  database:
    platform: linux/arm64
    restart: always
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 3306:3306