services:
  web:
    platform: linux/arm64
    restart: always
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web/src:/myfolder/src
    ports:
      - 3000:3000
    env_file:
      - ./web/.env.docker

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"

  vote-counter:
    platform: linux/arm64
    restart: always
    build:
      context: ./voteCounter
      dockerfile: Dockerfile
    ports:
      - 4002:4002
    env_file:
      - ./voteCounter/.dev.env
    depends_on:
      - rabbitmq

  room-scheduler:
    platform: linux/arm64
    restart: always
    build:
      context: ./roomScheduler
      dockerfile: Dockerfile
    ports:
      - 4001:4001
    env_file:
      - ./roomScheduler/.dev.env
    depends_on:
      - rabbitmq
  
  blockchain-node1:
    platform: linux/arm64
    restart: always
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    ports:
      - 4004:4004
    environment:
      PORT: "${NODE1}"
    volumes:
      - didi_blockchain_db1:/blockchain.db
      - ./blockchain/start.sh:/app/start.sh
    command: ["/bin/sh", "/app/start.sh"]
  
  blockchain-node2:
    platform: linux/arm64
    restart: always
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    ports:
      - 4005:4005
    environment:
      PORT: "${NODE2}"
    volumes:
      - didi_blockchain_db2:/blockchain.db

  blockchain-node3:
    platform: linux/arm64
    restart: always
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    ports:
      - 4006:4006
    environment:
      PORT: "${NODE3}"
    volumes:
      - didi_blockchain_db3:/blockchain.db

  database:
    platform: linux/arm64
    restart: always
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: "${WEB_DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${WEB_DB_PASSWORD}"
    ports:
      - 3306:3306
    volumes:
      - didi_web_db:/var/lib/mysql
  
  scheduler-database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: "${SCHE_DB_USER}"
      POSTGRES_PASSWORD: "${SCHE_DB_PASSWORD}"
      POSTGRES_DB: "${SCHE_DB_NAME}"
    ports:
      - 5432:5432
    volumes:
      - didi_scheduler_db:/var/lib/postgresql/data

volumes:
  didi_web_db:
  didi_scheduler_db:
  didi_blockchain_db1:
  didi_blockchain_db2:
  didi_blockchain_db3: